# Generated by Django 4.0.10 on 2023-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('coingecko_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.FloatField(default=0)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
