# Generated by Django 4.0.10 on 2023-04-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='tag',
            new_name='symbol',
        ),
    ]
