# Generated by Django 4.0.10 on 2023-04-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
