# Generated by Django 4.0.10 on 2023-04-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_coin_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='coingecko_id',
            new_name='coin_id',
        ),
    ]
