# Generated by Django 4.0.10 on 2023-04-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
