# Generated by Django 4.0.10 on 2023-04-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='price',
        ),
    ]
