# Generated by Django 4.0.10 on 2023-04-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_coin_market_cap_remove_coin_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='market_cap',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
