# Generated by Django 4.0.10 on 2023-04-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_coin_coin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
