# Generated by Django 4.0.10 on 2023-04-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_vote_vote_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
