# Generated by Django 4.0.10 on 2023-04-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_vote_vote_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
