# Generated by Django 4.0.10 on 2023-04-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_coin_coin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_id',
            field=models.CharField(max_length=255),
        ),
    ]
