# Generated by Django 4.0.10 on 2023-04-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_coin_coin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='votes',
        ),
        migrations.AddField(
            model_name='coin',
            name='votes',
            field=models.ManyToManyField(to='core.vote'),
        ),
    ]
