# Generated by Django 4.0.10 on 2023-04-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_vote_coin_remove_coin_votes_coin_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='votes',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
