# Generated by Django 4.0.10 on 2023-05-01 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_vote_coin_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='votes',
        ),
        migrations.AddField(
            model_name='vote',
            name='coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.coin'),
            preserve_default=False,
        ),
    ]
