# Generated by Django 4.0.10 on 2023-05-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_coin_votes_vote_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='votes_left',
            field=models.IntegerField(default=3),
        ),
    ]
