# Generated by Django 4.0.10 on 2023-05-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_votes_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='reason',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
