# Generated by Django 4.0.10 on 2023-05-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_coin_price_change_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price_change_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
