# Generated by Django 4.0.10 on 2023-05-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_coin_price_change_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
