# Generated by Django 4.0.10 on 2023-05-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_vote_created_at_vote_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price_change_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
