# Generated by Django 4.0.10 on 2023-05-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_coin_price_change_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price_change_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, null=True),
        ),
    ]
